export const userRawNesting = {
  blackboards: true,
  blackboardsReceived: true,
  classes: true,
  clubs: true,
  clubsAsLeader: true,
  courses: true,
  coursesAsTeacher: true,
  events: true,
  eventTickets: true,
  messages: true,
  schools: false,
  userAccount: true,
  userChats: true,
};

export const userNesting = {
  blackboards: {},
  blackboardsReceived: {},
  classes: {},
  clubs: {},
  clubsAsLeader: {},
  courses: {},
  coursesAsTeacher: {},
  events: {},
  eventTickets: {},
  messages: {},
  schools: false,
  userAccount: {},
  userChats: {},
};
