export const userRawNesting = {
  activities: true,
  blackboards: true,
  blackboardsReceived: true,
  classes: true,
  clubs: true,
  clubsAsLeader: true,
  courses: true,
  coursesAsTeacher: true,
  events: true,
  eventTickets: true,
  readActivities: true,
  schools: false,
  targetActivities: true,
  userAccount: true,
  userChats: true,
};

export const userNesting = {
  activities: {},
  blackboards: {},
  blackboardsReceived: {},
  classes: {},
  clubs: {},
  clubsAsLeader: {},
  courses: {},
  coursesAsTeacher: {},
  events: {},
  eventTickets: {},
  readActivities: {},
  schools: false,
  targetActivities: {},
  userAccount: {},
  userChats: {},
};
