import { Module } from '@nestjs/common';
import {
  AuthModule,
  BlackboardModule,
  BlackboardTagModule,
  ChatModule,
  ChatService,
  ClassController,
  ClassModule,
  ClassService,
  ClubModule,
  ClubService,
  ClubTagController,
  ClubTagModule,
  ClubTagService,
  CourseModule,
  EventController,
  EventModule,
  EventService,
  EventTicketModule,
  GradeController,
  GradeModule,
  MessageController,
  MessageModule,
  MessageService,
  PrismaModule,
  SchoolController,
  SchoolModule,
  SchoolService,
  SetupAccountModule,
  SubjectController,
  SubjectModule,
  SubjectService,
  UserAccountModule,
  UserChatController,
  UserChatModule,
  UserChatService,
  UserModule,
} from './';
import { ConfigModule } from '@nestjs/config';

@Module({
  imports: [
    AuthModule,
    UserAccountModule,
    PrismaModule,
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    BlackboardModule,
    BlackboardTagModule,
    ChatModule,
    ClassModule,
    ClubModule,
    ClubTagModule,
    CourseModule,
    EventModule,
    EventTicketModule,
    GradeModule,
    MessageModule,
    SchoolModule,
    SetupAccountModule,
    SubjectModule,
    UserModule,
    UserChatModule,
  ],
  providers: [
    ChatService,
    ClassService,
    ClubService,
    ClubTagService,
    EventService,
    MessageService,
    SchoolService,
    SubjectService,
    UserChatService,
  ],
  controllers: [
    ClassController,
    ClubTagController,
    EventController,
    GradeController,
    MessageController,
    SchoolController,
    SubjectController,
    UserChatController,
  ],
})
export class AppModule {}
